### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by benedekrozemberczki** [PetarV-/TikZ#2]
Dear Petar,

Thanks for the hard work, these plots are amazing. I am planning to use a heavily modified version of the DGI plot in a paper (it describes a multi-scale node embedding procedure). How can I give proper attribution besides a citation?

Bests,

Benedek

**Comment by PetarV-** [comment]
Hi Benedek, 

Thanks for your note and I'm very happy you found the material useful! :)
If you've substantially altered the figure, no attribution is necessary. 
But you are of course welcome to include a citation on where the figure was inspired from, should your paper allow space for that.

Thanks,
Petar
